include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    avoid_positional_boolean_parameters: false
    non_constant_identifier_names: false