name: roumo_flutter
description: ROUMO Flutter Project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7

  # State Management
  flutter_riverpod: ^2.4.1
  equatable: ^2.0.5
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

  # Network
  dio: ^5.3.3

  # Social Login
  google_sign_in: ^6.1.5
  flutter_naver_login: ^1.8.0
  sign_in_with_apple: ^5.0.0

  # Route
  go_router: ^11.0.0

  # Utils
  intl: ^0.18.1
  logger:

  # Firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0

  # Local Storage
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  json_serializable:

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700

flutter_intl:
  enabled: true
flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
